apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: elasticsearch-backup
spec:
  schedule: "0 0 * * *" # run backup job every day at  midnight
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: elasticsearch-backup
              image: elasticsearch-assigment-image:v1.0
              env:
                - name: ELASTICSEARCH_URL
                  value: "http://elasticsearch:9200"
              # Add other necessary environment variables
          restartPolicy: OnFailure
